arrowParens: always
bracketSameLine: false
bracketSpacing: true
endOfLine: lf
insertPragma: false
printWidth: 160
proseWrap: preserve
quoteProps: as-needed
requirePragma: false
semi: true
singleAttributePerLine: false
singleQuote: false
tabWidth: 4
trailingComma: all
useTabs: false
overrides:
  - files:
      - "*.yml"
    options:
      tabWidth: 2
